#!/usr/bin/env python3
"""Build minimal Clash/Hako profiles for 回国 (backcn) or 出国 (cnip)."""
from __future__ import annotations

import argparse
import ipaddress
import sys
from pathlib import Path

CN_DOMAIN_URL = (
    "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/"
    "meta/geo/geosite/cn.mrs"
)
CN_IP_URL = (
    "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/"
    "meta/geo/geoip/cn.mrs"
)
ADS_URL = (
    "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/"
    "meta/geo/geosite/category-ads-all.mrs"
)
YOUTUBE_URL = (
    "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/"
    "meta/geo/geosite/youtube.mrs"
)
PROVIDER_PLACEHOLDER = "https://example.invalid/replace-with-private-mihomo-profile.yaml"
CN_DNS = "https://223.5.5.5/dns-query"


def load_domains(path: str) -> list[str]:
    domains: list[str] = []
    seen: set[str] = set()
    for line_number, raw in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
        value = raw.strip().lower().rstrip(".")
        if not value or value.startswith("#"):
            continue
        if "," in value or " " in value or "." not in value:
            raise SystemExit(f"error: invalid domain at {path}:{line_number}: {raw}")
        if value not in seen:
            seen.add(value)
            domains.append(value)
    return domains


def load_direct_rules(path: str) -> list[str]:
    rules: list[str] = []
    for line_number, raw in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = [field.strip().lower() for field in line.split(",")]
        match fields:
            case ["ip-cidr", network] if network:
                try:
                    parsed = ipaddress.ip_network(network, strict=True)
                except ValueError as exc:
                    raise SystemExit(
                        f"error: invalid IP network at {path}:{line_number}: {raw}"
                    ) from exc
                kind = "IP-CIDR" if parsed.version == 4 else "IP-CIDR6"
                rules.append(f"{kind},{parsed},DIRECT,no-resolve")
            case ["domain-suffix", domain] if domain:
                rules.append(f"DOMAIN-SUFFIX,{domain.rstrip('.')},DIRECT")
            case ["protocol-port", protocol, port] if protocol in {"tcp", "udp"}:
                if not port.isdigit() or not 1 <= int(port) <= 65535:
                    raise SystemExit(f"error: invalid port at {path}:{line_number}: {raw}")
                rules.append(f"AND,((NETWORK,{protocol}),(DST-PORT,{port})),DIRECT")
            case _:
                raise SystemExit(f"error: invalid direct intent at {path}:{line_number}: {raw}")
    return rules


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(profile: str, domains: list[str], direct_rules: list[str], dns: str) -> str:
    cn_policy = "PROXY" if profile == "backcn" else "DIRECT"
    fallback = "DIRECT" if profile == "backcn" else "PROXY"
    cn_dns_route = "PROXY" if profile == "backcn" else "DIRECT"
    foreign_dns_route = "DIRECT" if profile == "backcn" else "PROXY"
    foreign_dns = dns or "https://1.1.1.1/dns-query"

    lines = [
        "# Generated by rulesv2. Replace the proxy-provider URL locally; never commit it.",
        f"# Profile: {profile} ({'CN via proxy, overseas direct' if profile == 'backcn' else 'CN direct, overseas via proxy'})",
        "mode: rule",
        "log-level: warning",
        "ipv6: true",
        "unified-delay: true",
        "tcp-concurrent: true",
        "profile:",
        "  store-selected: true",
        "  store-fake-ip: true",
        "dns:",
        "  enable: true",
        "  ipv6: true",
        "  enhanced-mode: fake-ip",
        "  fake-ip-range: 198.18.0.1/16",
        "  use-hosts: true",
        "  fake-ip-filter:",
        '    - "+.lan"',
        '    - "+.local"',
        "  default-nameserver:",
        "    - system",
        "  proxy-server-nameserver:",
        "    - system",
        "  nameserver:",
        f"    - {quote(foreign_dns + '#' + foreign_dns_route)}",
        "  nameserver-policy:",
        f"    {quote('rule-set:youtube')}: {quote(foreign_dns + '#YouTube')}",
        f"    {quote('rule-set:cn-domain')}: {quote(CN_DNS + '#' + cn_dns_route)}",
    ]
    for domain in domains:
        lines.append(
            f"    {quote('+.' + domain)}: "
            f"{quote(CN_DNS + '#' + cn_dns_route)}"
        )

    lines.extend([
        "proxy-providers:",
        "  private-provider:",
        "    type: http",
        f"    url: {quote(PROVIDER_PLACEHOLDER)}",
        "    path: ./providers/private-provider.yaml",
        "    interval: 21600",
        "    health-check:",
        "      enable: true",
        '      url: "https://www.gstatic.com/generate_204"',
        "      interval: 600",
        "      lazy: true",
        "proxy-groups:",
        "  - name: PROXY",
        "    type: select",
        "    proxies:",
        "      - REJECT",
        "    use:",
        "      - private-provider",
        "  - name: YouTube",
        "    type: select",
        "    proxies:",
        "      - PROXY",
        "      - DIRECT",
        "    use:",
        "      - private-provider",
        "rule-providers:",
        "  cn-domain:",
        "    type: http",
        "    behavior: domain",
        "    format: mrs",
        f"    url: {quote(CN_DOMAIN_URL)}",
        "    path: ./rules/cn-domain.mrs",
        "    interval: 86400",
        "  cn-ip:",
        "    type: http",
        "    behavior: ipcidr",
        "    format: mrs",
        f"    url: {quote(CN_IP_URL)}",
        "    path: ./rules/cn-ip.mrs",
        "    interval: 86400",
        "  ads:",
        "    type: http",
        "    behavior: domain",
        "    format: mrs",
        f"    url: {quote(ADS_URL)}",
        "    path: ./rules/ads.mrs",
        "    interval: 86400",
        "  youtube:",
        "    type: http",
        "    behavior: domain",
        "    format: mrs",
        f"    url: {quote(YOUTUBE_URL)}",
        "    path: ./rules/youtube.mrs",
        "    interval: 86400",
        "rules:",
        "  - DOMAIN,pikvm.kbyshiyori.com,DIRECT",
    ])
    lines.extend(f"  - {rule}" for rule in direct_rules)
    lines.extend(f"  - DOMAIN-SUFFIX,{domain},{cn_policy}" for domain in domains)
    lines.extend([
        "  - RULE-SET,youtube,YouTube",
        "  - RULE-SET,ads,REJECT",
        "  - RULE-SET,cn-domain," + cn_policy,
        "  - RULE-SET,cn-ip," + cn_policy + ",no-resolve",
        "  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
        "  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
        "  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
        "  - IP-CIDR6,fc00::/7,DIRECT,no-resolve",
        "  - MATCH," + fallback,
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=["backcn", "cnip"], required=True)
    parser.add_argument("--rules", required=True, help="path to redirect-to-cn.list")
    parser.add_argument("--direct-rules", required=True, help="path to direct.list")
    parser.add_argument("--dns", default="", help="foreign DoH URL; defaults to Cloudflare")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    domains = load_domains(args.rules)
    direct_rules = load_direct_rules(args.direct_rules)
    text = render(args.profile, domains, direct_rules, args.dns)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(
        f"built {out} | profile={args.profile} | direct={len(direct_rules)} | "
        f"redirect-to-cn={len(domains)} | dns={'custom' if args.dns else 'cloudflare'}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
